export default {
	cognito: {
		USER_POOL_ID : 'us-west-2_0qaUPcZji',
		APP_CLIENT_ID : '5ipfum8vk70ueoek214ftrmm90',
		IDENTITY_POOL_ID: 'us-west-2:7782c50d-441b-4495-ab4d-0bdd81b8dcb0',
		REGION: 'us-west-2'
	},

	apiGateway: {
		cards: {
			URL: 'https://1xh0wwfkjf.execute-api.us-west-1.amazonaws.com/prod',
			REGION: 'us-west-1'
		},
		feeds: {
			URL: 'https://wu7nsd6i3a.execute-api.us-west-1.amazonaws.com/prod',
			REGION: 'us-west-1'	
		}
	},

	s3: {
		cards: {
			BUCKET: 'controversy-cards-images',
			URL: 'https://s3-us-west-2.amazonaws.com/controversy-cards-images/',
			REGION: 'us-west-2'
		},
		feeds: {
			BUCKET: 'controversy-cards-feeds',
			URL: 'https://s3-us-west-2.amazonaws.com/controversy-cards-feeds/',
			REGION: 'us-west-2'
		}
	},

	cloudfront: {
		BUCKET: 'd2rubbqaoavtmn.cloudfront.net',
		REGION: 'us-west-1'
	},

	categories: [
		{text: 'All'},

		{text: 'Controversy Cards'},
		{text: 'Quotes'},
		{text: 'Feed Posts'},
		{text: 'Comments'},

		{text: 'Cards/Feeds: critique'},
		{text: 'Cards/Feeds: historical'},
		{text: 'Cards/Feeds: ongoing'},
		{text: 'Cards/Feeds: person'},
		{text: 'Cards/Feeds: reform'},
		{text: 'Cards/Feeds: thinking'},

		{text: 'Quotes: aether'},
		{text: 'Quotes: alfven'},
		{text: 'Quotes: aliens'},
		{text: 'Quotes: alternative medicine'},
		{text: 'Quotes: anomalies'},
		{text: 'Quotes: assumptions'},
		{text: 'Quotes: astrologers'},
		{text: 'Quotes: astronomy'},
		{text: 'Quotes: astrophysics'},
		{text: 'Quotes: bias'},
		{text: 'Quotes: big bang'},
		{text: 'Quotes: biology'},
		{text: 'Quotes: birkeland'},
		{text: 'Quotes: black holes'},
		{text: 'Quotes: brain'},
		{text: 'Quotes: catastrophism'},
		{text: 'Quotes: change'},
		{text: 'Quotes: charles bruce'},
		{text: 'Quotes: chemistry'},
		{text: 'Quotes: chiropractic'},
		{text: 'Quotes: civ'},
		{text: 'Quotes: climate'},
		{text: 'Quotes: comets'},
		{text: 'Quotes: consensus'},
		{text: 'Quotes: conspiracy'},
		{text: 'Quotes: constants'},
		{text: 'Quotes: controversy'},
		{text: 'Quotes: cosmic plasma'},
		{text: 'Quotes: cosmology'},
		{text: 'Quotes: crackpots / cranks'},
		{text: 'Quotes: cranks'},
		{text: 'Quotes: craters'},
		{text: 'Quotes: creativity'},
		{text: 'Quotes: critique'},
		{text: 'Quotes: crowdsourcing'},
		{text: 'Quotes: dark matter'},
		{text: 'Quotes: dawkins'},
		{text: 'Quotes: death'},
		{text: 'Quotes: debate'},
		{text: 'Quotes: discovery'},
		{text: 'Quotes: dissent / heresy'},
		{text: 'Quotes: doctors / medicine'},
		{text: 'Quotes: education'},
		{text: 'Quotes: electric sun'},
		{text: 'Quotes: electricity in space'},
		{text: 'Quotes: electromagnetism'},
		{text: 'Quotes: empty space'},
		{text: 'Quotes: engineers'},
		{text: 'Quotes: entertainment'},
		{text: 'Quotes: epistemology'},
		{text: 'Quotes: establishment'},
		{text: 'Quotes: evolution'},
		{text: 'Quotes: experts'},
		{text: 'Quotes: facts'},
		{text: 'Quotes: fads'},
		{text: 'Quotes: failed predictions'},
		{text: 'Quotes: focus'},
		{text: 'Quotes: fraud'},
		{text: 'Quotes: funding'},
		{text: 'Quotes: galaxies'},
		{text: 'Quotes: galileo'},
		{text: 'Quotes: genius'},
		{text: 'Quotes: geology'},
		{text: 'Quotes: goddard'},
		{text: 'Quotes: gravitational waves'},
		{text: 'Quotes: gravity'},
		{text: 'Quotes: heat death'},
		{text: 'Quotes: higgs boson'},
		{text: 'Quotes: history of science'},
		{text: 'Quotes: homeopathy'},
		{text: 'Quotes: hypothesis'},
		{text: 'Quotes: ideology'},
		{text: 'Quotes: ieee'},
		{text: 'Quotes: ignorance'},
		{text: 'Quotes: internet'},
		{text: 'Quotes: jargon / language / symbols'},
		{text: 'Quotes: journalism'},
		{text: 'Quotes: journals'},
		{text: 'Quotes: judgment'},
		{text: 'Quotes: knowledge'},
		{text: 'Quotes: language'},
		{text: 'Quotes: life'},
		{text: 'Quotes: light'},
		{text: 'Quotes: lightning'},
		{text: 'Quotes: listening'},
		{text: 'Quotes: lorentz'},
		{text: 'Quotes: magnetic fields'},
		{text: 'Quotes: magnetic reconnection'},
		{text: 'Quotes: mammoths'},
		{text: 'Quotes: marklund convection'},
		{text: 'Quotes: mars'},
		{text: 'Quotes: math'},
		{text: 'Quotes: mavericks'},
		{text: 'Quotes: maxwell'},
		{text: 'Quotes: mechanistic worldview'},
		{text: 'Quotes: metaphysics'},
		{text: 'Quotes: meteorites'},
		{text: 'Quotes: modeling'},
		{text: 'Quotes: moon'},
		{text: 'Quotes: mythology'},
		{text: 'Quotes: natural philosophy'},
		{text: 'Quotes: nebulae'},
		{text: 'Quotes: neutron stars'},
		{text: 'Quotes: new ideas'},
		{text: 'Quotes: newton'},
		{text: 'Quotes: nobel'},
		{text: 'Quotes: novae'},
		{text: 'Quotes: occams razor'},
		{text: 'Quotes: oliver lodge'},
		{text: 'Quotes: opportunity'},
		{text: 'Quotes: orthodoxy'},
		{text: 'Quotes: paradigm'},
		{text: 'Quotes: parapsychology'},
		{text: 'Quotes: particles'},
		{text: 'Quotes: peer review'},
		{text: 'Quotes: pet theory'},
		{text: 'Quotes: philosophy'},
		{text: 'Quotes: physicist'},
		{text: 'Quotes: planetary formation'},
		{text: 'Quotes: plasma'},
		{text: 'Quotes: plasma focus'},
		{text: 'Quotes: politics'},
		{text: 'Quotes: predictions'},
		{text: 'Quotes: professionals'},
		{text: 'Quotes: progress'},
		{text: 'Quotes: provisional'},
		{text: 'Quotes: pseudoscience'},
		{text: 'Quotes: pseudoskepticism'},
		{text: 'Quotes: psychology'},
		{text: 'Quotes: quantum mechanics'},
		{text: 'Quotes: reason'},
		{text: 'Quotes: redshift'},
		{text: 'Quotes: relativity'},
		{text: 'Quotes: religion'},
		{text: 'Quotes: research'},
		{text: 'Quotes: resonance'},
		{text: 'Quotes: rupert sheldrake'},
		{text: 'Quotes: sand'},
		{text: 'Quotes: science'},
		{text: 'Quotes: science court'},
		{text: 'Quotes: scientific method'},
		{text: 'Quotes: scientism'},
		{text: 'Quotes: scientists'},
		{text: 'Quotes: settled science'},
		{text: 'Quotes: sherlock holmes'},
		{text: 'Quotes: skeptical inquirer'},
		{text: 'Quotes: skepticism'},
		{text: 'Quotes: sociology'},
		{text: 'Quotes: solar'},
		{text: 'Quotes: space'},
		{text: 'Quotes: specialization'},
		{text: 'Quotes: statistics'},
		{text: 'Quotes: stellar formation'},
		{text: 'Quotes: string theory'},
		{text: 'Quotes: superstition'},
		{text: 'Quotes: synthesis'},
		{text: 'Quotes: technology'},
		{text: 'Quotes: tesla'},
		{text: 'Quotes: theory'},
		{text: 'Quotes: truth'},
		{text: 'Quotes: uncertainty / certainty'},
		{text: 'Quotes: understanding'},
		{text: 'Quotes: unification'},
		{text: 'Quotes: universe'},
		{text: 'Quotes: velikovsky'},
		{text: 'Quotes: venus'},
		{text: 'Quotes: village venus'},
		{text: 'Quotes: water'},
		{text: 'Quotes: wisdom'},
		{text: 'Quotes: witty'},
		{text: 'Quotes: worldviews'}
	]
};
