export default {
	cognito: {
		USER_POOL_ID : 'us-west-2_0qaUPcZji',
		APP_CLIENT_ID : '5ipfum8vk70ueoek214ftrmm90',
		IDENTITY_POOL_ID: 'us-west-2:7782c50d-441b-4495-ab4d-0bdd81b8dcb0',
		REGION: 'us-west-2'
	},

	apiGateway: {
		cards: {
			URL: 'https://1xh0wwfkjf.execute-api.us-west-1.amazonaws.com/prod',
			REGION: 'us-west-1'
		},
		feeds: {
			URL: 'https://wu7nsd6i3a.execute-api.us-west-1.amazonaws.com/prod',
			REGION: 'us-west-1'	
		}
	},

	s3: {
		cards: {
			BUCKET: 'controversy-cards-images',
			URL: 'https://s3-us-west-2.amazonaws.com/controversy-cards-images/',
			REGION: 'us-west-2'
		},
		feeds: {
			BUCKET: 'controversy-cards-feeds',
			URL: 'https://s3-us-west-2.amazonaws.com/controversy-cards-feeds/',
			REGION: 'us-west-2'
		}
	},

	cloudfront: {
		BUCKET: 'd2rubbqaoavtmn.cloudfront.net',
		REGION: 'us-west-1'
	},

	categories: [
		{text: 'All', icons: null},

		{text: 'Controversy Cards', icons: null},
		{text: 'Quotes', icons: null},
		{text: 'Feed Posts', icons: null},
		{text: 'Comments', icons: null},

		{text: 'Cards/Feeds: critique', icons: null},
		{text: 'Cards/Feeds: historical', icons: null},
		{text: 'Cards/Feeds: ongoing', icons: null},
		{text: 'Cards/Feeds: person', icons: null},
		{text: 'Cards/Feeds: reform', icons: null},
		{text: 'Cards/Feeds: thinking', icons: null},

		{text: 'Quotes: aether', icons: ''},
		{text: 'Quotes: alfven', icons: ''},
		{text: 'Quotes: aliens', icons: ''},
		{text: 'Quotes: alternative medicine', icons: ''},
		{text: 'Quotes: anomalies', icons: ''},
		{text: 'Quotes: assumptions', icons: ''},
		{text: 'Quotes: astrologers', icons: ''},
		{text: 'Quotes: astronomy', icons: ''},
		{text: 'Quotes: astrophysics', icons: ''},
		{text: 'Quotes: bias', icons: ''},
		{text: 'Quotes: big bang', icons: ''},
		{text: 'Quotes: biology', icons: ''},
		{text: 'Quotes: birkeland', icons: ''},
		{text: 'Quotes: black holes', icons: ''},
		{text: 'Quotes: brain', icons: ''},
		{text: 'Quotes: catastrophism', icons: ''},
		{text: 'Quotes: change', icons: ''},
		{text: 'Quotes: charles bruce', icons: ''},
		{text: 'Quotes: chemistry', icons: ''},
		{text: 'Quotes: chiropractic', icons: ''},
		{text: 'Quotes: civ', icons: ''},
		{text: 'Quotes: climate', icons: ''},
		{text: 'Quotes: comets', icons: ''},
		{text: 'Quotes: consensus', icons: ''},
		{text: 'Quotes: conspiracy', icons: ''},
		{text: 'Quotes: constants', icons: ''},
		{text: 'Quotes: controversy', icons: ''},
		{text: 'Quotes: cosmic plasma', icons: ''},
		{text: 'Quotes: cosmology', icons: ''},
		{text: 'Quotes: crackpots / cranks', icons: ''},
		{text: 'Quotes: cranks', icons: ''},
		{text: 'Quotes: craters', icons: ''},
		{text: 'Quotes: creativity', icons: ''},
		{text: 'Quotes: critique', icons: ''},
		{text: 'Quotes: crowdsourcing', icons: ''},
		{text: 'Quotes: dark matter', icons: ''},
		{text: 'Quotes: dawkins', icons: ''},
		{text: 'Quotes: death', icons: ''},
		{text: 'Quotes: debate', icons: ''},
		{text: 'Quotes: discovery', icons: ''},
		{text: 'Quotes: dissent / heresy', icons: ''},
		{text: 'Quotes: doctors / medicine', icons: ''},
		{text: 'Quotes: education', icons: ''},
		{text: 'Quotes: electric sun', icons: ''},
		{text: 'Quotes: electricity in space', icons: ''},
		{text: 'Quotes: electromagnetism', icons: ''},
		{text: 'Quotes: empty space', icons: ''},
		{text: 'Quotes: engineers', icons: ''},
		{text: 'Quotes: entertainment', icons: ''},
		{text: 'Quotes: epistemology', icons: ''},
		{text: 'Quotes: establishment', icons: ''},
		{text: 'Quotes: evolution', icons: ''},
		{text: 'Quotes: experts', icons: ''},
		{text: 'Quotes: facts', icons: ''},
		{text: 'Quotes: fads', icons: ''},
		{text: 'Quotes: failed predictions', icons: ''},
		{text: 'Quotes: focus', icons: ''},
		{text: 'Quotes: fraud', icons: ''},
		{text: 'Quotes: funding', icons: ''},
		{text: 'Quotes: galaxies', icons: ''},
		{text: 'Quotes: galileo', icons: ''},
		{text: 'Quotes: genius', icons: ''},
		{text: 'Quotes: geology', icons: ''},
		{text: 'Quotes: goddard', icons: ''},
		{text: 'Quotes: gravitational waves', icons: ''},
		{text: 'Quotes: gravity', icons: ''},
		{text: 'Quotes: heat death', icons: ''},
		{text: 'Quotes: higgs boson', icons: ''},
		{text: 'Quotes: history of science', icons: ''},
		{text: 'Quotes: homeopathy', icons: ''},
		{text: 'Quotes: hypothesis', icons: ''},
		{text: 'Quotes: ideology', icons: ''},
		{text: 'Quotes: ieee', icons: ''},
		{text: 'Quotes: ignorance', icons: ''},
		{text: 'Quotes: internet', icons: ''},
		{text: 'Quotes: jargon / language / symbols', icons: ''},
		{text: 'Quotes: journalism', icons: ''},
		{text: 'Quotes: journals', icons: ''},
		{text: 'Quotes: judgment', icons: ''},
		{text: 'Quotes: knowledge', icons: ''},
		{text: 'Quotes: language', icons: ''},
		{text: 'Quotes: life', icons: ''},
		{text: 'Quotes: light', icons: ''},
		{text: 'Quotes: lightning', icons: ''},
		{text: 'Quotes: listening', icons: ''},
		{text: 'Quotes: lorentz', icons: ''},
		{text: 'Quotes: magnetic fields', icons: ''},
		{text: 'Quotes: magnetic reconnection', icons: ''},
		{text: 'Quotes: mammoths', icons: ''},
		{text: 'Quotes: marklund convection', icons: ''},
		{text: 'Quotes: mars', icons: ''},
		{text: 'Quotes: math', icons: ''},
		{text: 'Quotes: mavericks', icons: ''},
		{text: 'Quotes: maxwell', icons: ''},
		{text: 'Quotes: mechanistic worldview', icons: ''},
		{text: 'Quotes: metaphysics', icons: ''},
		{text: 'Quotes: meteorites', icons: ''},
		{text: 'Quotes: modeling', icons: ''},
		{text: 'Quotes: moon', icons: ''},
		{text: 'Quotes: mythology', icons: ''},
		{text: 'Quotes: natural philosophy', icons: ''},
		{text: 'Quotes: nebulae', icons: ''},
		{text: 'Quotes: neutron stars', icons: ''},
		{text: 'Quotes: new ideas', icons: ''},
		{text: 'Quotes: newton', icons: ''},
		{text: 'Quotes: nobel', icons: ''},
		{text: 'Quotes: novae', icons: ''},
		{text: 'Quotes: occams razor', icons: ''},
		{text: 'Quotes: oliver lodge', icons: ''},
		{text: 'Quotes: opportunity', icons: ''},
		{text: 'Quotes: orthodoxy', icons: ''},
		{text: 'Quotes: paradigm', icons: ''},
		{text: 'Quotes: parapsychology', icons: ''},
		{text: 'Quotes: particles', icons: ''},
		{text: 'Quotes: peer review', icons: ''},
		{text: 'Quotes: pet theory', icons: ''},
		{text: 'Quotes: philosophy', icons: ''},
		{text: 'Quotes: physicist', icons: ''},
		{text: 'Quotes: planetary formation', icons: ''},
		{text: 'Quotes: plasma', icons: ''},
		{text: 'Quotes: plasma focus', icons: ''},
		{text: 'Quotes: politics', icons: ''},
		{text: 'Quotes: predictions', icons: ''},
		{text: 'Quotes: professionals', icons: ''},
		{text: 'Quotes: progress', icons: ''},
		{text: 'Quotes: provisional', icons: ''},
		{text: 'Quotes: pseudoscience', icons: ''},
		{text: 'Quotes: pseudoskepticism', icons: ''},
		{text: 'Quotes: psychology', icons: ''},
		{text: 'Quotes: quantum mechanics', icons: ''},
		{text: 'Quotes: reason', icons: ''},
		{text: 'Quotes: redshift', icons: ''},
		{text: 'Quotes: relativity', icons: ''},
		{text: 'Quotes: religion', icons: ''},
		{text: 'Quotes: research', icons: ''},
		{text: 'Quotes: resonance', icons: ''},
		{text: 'Quotes: rupert sheldrake', icons: ''},
		{text: 'Quotes: sand', icons: ''},
		{text: 'Quotes: science', icons: ''},
		{text: 'Quotes: science court', icons: ''},
		{text: 'Quotes: scientific method', icons: ''},
		{text: 'Quotes: scientism', icons: ''},
		{text: 'Quotes: scientists', icons: ''},
		{text: 'Quotes: settled science', icons: ''},
		{text: 'Quotes: sherlock holmes', icons: ''},
		{text: 'Quotes: skeptical inquirer', icons: ''},
		{text: 'Quotes: skepticism', icons: ''},
		{text: 'Quotes: sociology', icons: ''},
		{text: 'Quotes: solar', icons: ''},
		{text: 'Quotes: space', icons: ''},
		{text: 'Quotes: specialization', icons: ''},
		{text: 'Quotes: statistics', icons: ''},
		{text: 'Quotes: stellar formation', icons: ''},
		{text: 'Quotes: string theory', icons: ''},
		{text: 'Quotes: superstition', icons: ''},
		{text: 'Quotes: synthesis', icons: ''},
		{text: 'Quotes: technology', icons: ''},
		{text: 'Quotes: tesla', icons: ''},
		{text: 'Quotes: theory', icons: ''},
		{text: 'Quotes: truth', icons: ''},
		{text: 'Quotes: uncertainty / certainty', icons: ''},
		{text: 'Quotes: understanding', icons: ''},
		{text: 'Quotes: unification', icons: ''},
		{text: 'Quotes: universe', icons: ''},
		{text: 'Quotes: velikovsky', icons: ''},
		{text: 'Quotes: venus', icons: ''},
		{text: 'Quotes: village venus', icons: ''},
		{text: 'Quotes: water', icons: ''},
		{text: 'Quotes: wisdom', icons: ''},
		{text: 'Quotes: witty', icons: ''},
		{text: 'Quotes: worldviews', icons: ''}
	]
};
