export default {
	breakpoint: {
		MOBILE: 767,
		TABLET: 1023, // DESKTOP everything greater
		LARGEST: 1400
	},

	cognito: {
		USER_POOL_ID : 'us-west-2_0qaUPcZji',
		APP_CLIENT_ID : '5ipfum8vk70ueoek214ftrmm90',
		IDENTITY_POOL_ID: 'us-west-2:7782c50d-441b-4495-ab4d-0bdd81b8dcb0',
		REGION: 'us-west-2'
	},

	apiGateway: {
		cards: {
			URL: 'https://1xh0wwfkjf.execute-api.us-west-1.amazonaws.com/prod',
			REGION: 'us-west-1'
		},
		feeds: {
			URL: 'https://wu7nsd6i3a.execute-api.us-west-1.amazonaws.com/prod',
			REGION: 'us-west-1'	
		}
	},

	s3: {
		cards: {
			BUCKET: 'controversy-cards-images',
			URL: 'https://s3-us-west-2.amazonaws.com/controversy-cards-images/',
			REGION: 'us-west-2'
		},
		feeds: {
			BUCKET: 'controversy-cards-feeds',
			URL: 'https://s3-us-west-2.amazonaws.com/controversy-cards-feeds/',
			REGION: 'us-west-2'
		}
	},

	cloudfront: {
		BUCKET: 'd2rubbqaoavtmn.cloudfront.net',
		REGION: 'us-west-1'
	},

	categories: [
		{text: 'All', keys: 'all'},

		{text: 'Controversy Cards', keys: 'con'},
		{text: 'Quotes', keys: 'quo'},
		{text: 'Feed Posts', keys: 'fee'},
		{text: 'Comments', keys: 'com'},

		{text: 'Cards/Feeds: critique', keys: 'cri'},
		{text: 'Cards/Feeds: historical', keys: 'his'},
		{text: 'Cards/Feeds: ongoing', keys: 'ong'},
		{text: 'Cards/Feeds: person', keys: 'per'},
		{text: 'Cards/Feeds: reform', keys: 'ref'},
		{text: 'Cards/Feeds: thinking', keys: 'thi'},

		{text: 'Quotes: aether', keys: 'A'},
		{text: 'Quotes: alfven', keys: ''},
		{text: 'Quotes: aliens', keys: ''},
		{text: 'Quotes: alternative medicine', keys: ''},
		{text: 'Quotes: anomalies', keys: ''},
		{text: 'Quotes: assumptions', keys: ''},
		{text: 'Quotes: astrologers', keys: ''},
		{text: 'Quotes: astronomy', keys: ''},
		{text: 'Quotes: astrophysics', keys: ''},
		{text: 'Quotes: bias', keys: 'B'},
		{text: 'Quotes: big bang', keys: ''},
		{text: 'Quotes: biology', keys: ''},
		{text: 'Quotes: birkeland', keys: ''},
		{text: 'Quotes: black holes', keys: ''},
		{text: 'Quotes: brain', keys: ''},
		{text: 'Quotes: catastrophism', keys: 'C'},
		{text: 'Quotes: change', keys: ''},
		{text: 'Quotes: charles bruce', keys: ''},
		{text: 'Quotes: chemistry', keys: ''},
		{text: 'Quotes: chiropractic', keys: ''},
		{text: 'Quotes: civ', keys: ''},
		{text: 'Quotes: climate', keys: ''},
		{text: 'Quotes: comets', keys: ''},
		{text: 'Quotes: consensus', keys: ''},
		{text: 'Quotes: conspiracy', keys: ''},
		{text: 'Quotes: constants', keys: ''},
		{text: 'Quotes: controversy', keys: ''},
		{text: 'Quotes: cosmic plasma', keys: ''},
		{text: 'Quotes: cosmology', keys: ''},
		{text: 'Quotes: crackpots / cranks', keys: ''},
		{text: 'Quotes: cranks', keys: ''},
		{text: 'Quotes: craters', keys: ''},
		{text: 'Quotes: creativity', keys: ''},
		{text: 'Quotes: critique', keys: ''},
		{text: 'Quotes: crowdsourcing', keys: ''},
		{text: 'Quotes: dark matter', keys: 'D'},
		{text: 'Quotes: dawkins', keys: ''},
		{text: 'Quotes: death', keys: ''},
		{text: 'Quotes: debate', keys: ''},
		{text: 'Quotes: discovery', keys: ''},
		{text: 'Quotes: dissent / heresy', keys: ''},
		{text: 'Quotes: doctors / medicine', keys: ''},
		{text: 'Quotes: education', keys: 'E'},
		{text: 'Quotes: electric sun', keys: ''},
		{text: 'Quotes: electricity in space', keys: ''},
		{text: 'Quotes: electromagnetism', keys: ''},
		{text: 'Quotes: empty space', keys: ''},
		{text: 'Quotes: engineers', keys: ''},
		{text: 'Quotes: entertainment', keys: ''},
		{text: 'Quotes: epistemology', keys: ''},
		{text: 'Quotes: establishment', keys: ''},
		{text: 'Quotes: evolution', keys: ''},
		{text: 'Quotes: experts', keys: ''},
		{text: 'Quotes: facts', keys: 'F'},
		{text: 'Quotes: fads', keys: ''},
		{text: 'Quotes: failed predictions', keys: ''},
		{text: 'Quotes: focus', keys: ''},
		{text: 'Quotes: fraud', keys: ''},
		{text: 'Quotes: funding', keys: ''},
		{text: 'Quotes: galaxies', keys: 'G'},
		{text: 'Quotes: galileo', keys: ''},
		{text: 'Quotes: genius', keys: ''},
		{text: 'Quotes: geology', keys: ''},
		{text: 'Quotes: goddard', keys: ''},
		{text: 'Quotes: gravitational waves', keys: ''},
		{text: 'Quotes: gravity', keys: ''},
		{text: 'Quotes: heat death', keys: 'H'},
		{text: 'Quotes: higgs boson', keys: ''},
		{text: 'Quotes: history of science', keys: ''},
		{text: 'Quotes: homeopathy', keys: ''},
		{text: 'Quotes: hypothesis', keys: ''},
		{text: 'Quotes: ideology', keys: 'I'},
		{text: 'Quotes: ieee', keys: ''},
		{text: 'Quotes: ignorance', keys: ''},
		{text: 'Quotes: internet', keys: ''},
		{text: 'Quotes: jargon / language / symbols', keys: 'J'},
		{text: 'Quotes: journalism', keys: ''},
		{text: 'Quotes: journals', keys: ''},
		{text: 'Quotes: judgment', keys: ''},
		{text: 'Quotes: knowledge', keys: 'K'},
		{text: 'Quotes: language', keys: 'L'},
		{text: 'Quotes: life', keys: ''},
		{text: 'Quotes: light', keys: ''},
		{text: 'Quotes: lightning', keys: ''},
		{text: 'Quotes: listening', keys: ''},
		{text: 'Quotes: lorentz', keys: ''},
		{text: 'Quotes: magnetic fields', keys: 'M'},
		{text: 'Quotes: magnetic reconnection', keys: ''},
		{text: 'Quotes: mammoths', keys: ''},
		{text: 'Quotes: marklund convection', keys: ''},
		{text: 'Quotes: mars', keys: ''},
		{text: 'Quotes: math', keys: ''},
		{text: 'Quotes: mavericks', keys: ''},
		{text: 'Quotes: maxwell', keys: ''},
		{text: 'Quotes: mechanistic worldview', keys: ''},
		{text: 'Quotes: metaphysics', keys: ''},
		{text: 'Quotes: meteorites', keys: ''},
		{text: 'Quotes: modeling', keys: ''},
		{text: 'Quotes: moon', keys: ''},
		{text: 'Quotes: mythology', keys: ''},
		{text: 'Quotes: natural philosophy', keys: 'N'},
		{text: 'Quotes: nebulae', keys: ''},
		{text: 'Quotes: neutron stars', keys: ''},
		{text: 'Quotes: new ideas', keys: ''},
		{text: 'Quotes: newton', keys: ''},
		{text: 'Quotes: nobel', keys: ''},
		{text: 'Quotes: novae', keys: ''},
		{text: 'Quotes: occams razor', keys: 'O'},
		{text: 'Quotes: oliver lodge', keys: ''},
		{text: 'Quotes: opportunity', keys: ''},
		{text: 'Quotes: orthodoxy', keys: ''},
		{text: 'Quotes: paradigm', keys: 'P'},
		{text: 'Quotes: parapsychology', keys: ''},
		{text: 'Quotes: particles', keys: ''},
		{text: 'Quotes: peer review', keys: ''},
		{text: 'Quotes: pet theory', keys: ''},
		{text: 'Quotes: philosophy', keys: ''},
		{text: 'Quotes: physicist', keys: ''},
		{text: 'Quotes: planetary formation', keys: ''},
		{text: 'Quotes: plasma', keys: ''},
		{text: 'Quotes: plasma focus', keys: ''},
		{text: 'Quotes: politics', keys: ''},
		{text: 'Quotes: predictions', keys: ''},
		{text: 'Quotes: professionals', keys: ''},
		{text: 'Quotes: progress', keys: ''},
		{text: 'Quotes: provisional', keys: ''},
		{text: 'Quotes: pseudoscience', keys: ''},
		{text: 'Quotes: pseudoskepticism', keys: ''},
		{text: 'Quotes: psychology', keys: ''},
		{text: 'Quotes: quantum mechanics', keys: 'Q'},
		{text: 'Quotes: reason', keys: 'R'},
		{text: 'Quotes: redshift', keys: ''},
		{text: 'Quotes: relativity', keys: ''},
		{text: 'Quotes: religion', keys: ''},
		{text: 'Quotes: research', keys: ''},
		{text: 'Quotes: resonance', keys: ''},
		{text: 'Quotes: rupert sheldrake', keys: ''},
		{text: 'Quotes: sand', keys: 'S'},
		{text: 'Quotes: science', keys: ''},
		{text: 'Quotes: science court', keys: ''},
		{text: 'Quotes: scientific method', keys: ''},
		{text: 'Quotes: scientism', keys: ''},
		{text: 'Quotes: scientists', keys: ''},
		{text: 'Quotes: settled science', keys: ''},
		{text: 'Quotes: sherlock holmes', keys: ''},
		{text: 'Quotes: skeptical inquirer', keys: ''},
		{text: 'Quotes: skepticism', keys: ''},
		{text: 'Quotes: sociology', keys: ''},
		{text: 'Quotes: solar', keys: ''},
		{text: 'Quotes: space', keys: ''},
		{text: 'Quotes: specialization', keys: ''},
		{text: 'Quotes: statistics', keys: ''},
		{text: 'Quotes: stellar formation', keys: ''},
		{text: 'Quotes: string theory', keys: ''},
		{text: 'Quotes: superstition', keys: ''},
		{text: 'Quotes: synthesis', keys: ''},
		{text: 'Quotes: technology', keys: 'T'},
		{text: 'Quotes: tesla', keys: ''},
		{text: 'Quotes: theory', keys: ''},
		{text: 'Quotes: truth', keys: ''},
		{text: 'Quotes: uncertainty / certainty', keys: 'U'},
		{text: 'Quotes: understanding', keys: ''},
		{text: 'Quotes: unification', keys: ''},
		{text: 'Quotes: universe', keys: ''},
		{text: 'Quotes: velikovsky', keys: 'V'},
		{text: 'Quotes: venus', keys: ''},
		{text: 'Quotes: village venus', keys: ''},
		{text: 'Quotes: water', keys: 'W'},
		{text: 'Quotes: wisdom', keys: ''},
		{text: 'Quotes: witty', keys: ''},
		{text: 'Quotes: worldviews', keys:''}
	]
};
